name: Deploy Offloop Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./doc

      - name: Build Docusaurus site
        run: npm run build
        working-directory: ./doc

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./doc
